create table candidates
(
    id              bigint generated by default as identity
        primary key,
    name            varchar(255) not null,
    price           varchar(255) not null,
    description     text         not null,
    working_mode_id bigint       not null
        constraint fk_working_mode_candidates
            references working_modes,
    photo           bytea        not null,
    created         timestamp    not null
);