create table posts
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255) not null,
    company     varchar(255) not null,
    description text         not null,
    created     timestamp    not null
);