create table working_modes
(
    id   bigint generated by default as identity
        primary key,
    mode varchar(30) not null
);

INSERT INTO working_modes values (1, 'REMOTELY');
INSERT INTO working_modes values (2, 'IN_THE_OFFICE');
INSERT INTO working_modes values (3, 'HYBRID');
